# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ardu_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 159)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 11, 1, 2)
        self.waveShapeBox = QtWidgets.QComboBox(self.centralwidget)
        self.waveShapeBox.setObjectName("waveShapeBox")
        self.waveShapeBox.addItem("")
        self.waveShapeBox.addItem("")
        self.gridLayout.addWidget(self.waveShapeBox, 2, 6, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 11, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 3, 1, 1, 1)
        self.portBox = QtWidgets.QComboBox(self.centralwidget)
        self.portBox.setObjectName("portBox")
        self.gridLayout.addWidget(self.portBox, 3, 2, 1, 10)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 11, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.trainDurEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trainDurEdit.setObjectName("trainDurEdit")
        self.gridLayout.addWidget(self.trainDurEdit, 0, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 9, 1, 1)
        self.pulseWidthEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulseWidthEdit.sizePolicy().hasHeightForWidth())
        self.pulseWidthEdit.setSizePolicy(sizePolicy)
        self.pulseWidthEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pulseWidthEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pulseWidthEdit.setObjectName("pulseWidthEdit")
        self.gridLayout.addWidget(self.pulseWidthEdit, 2, 10, 1, 1)
        self.pretrainDurEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pretrainDurEdit.setObjectName("pretrainDurEdit")
        self.gridLayout.addWidget(self.pretrainDurEdit, 0, 9, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 8, 1, 1)
        self.waitEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.waitEdit.setObjectName("waitEdit")
        self.gridLayout.addWidget(self.waitEdit, 2, 4, 1, 1)
        self.patternRepeatsBox = QtWidgets.QSpinBox(self.centralwidget)
        self.patternRepeatsBox.setMinimum(1)
        self.patternRepeatsBox.setMaximum(999)
        self.patternRepeatsBox.setObjectName("patternRepeatsBox")
        self.gridLayout.addWidget(self.patternRepeatsBox, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 5, 1, 1)
        self.freqPatternEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.freqPatternEdit.setObjectName("freqPatternEdit")
        self.gridLayout.addWidget(self.freqPatternEdit, 1, 4, 1, 7)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_Settings.setObjectName("actionLoad_Settings")
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arduino Stimulator"))
        self.label_9.setText(_translate("MainWindow", "s"))
        self.waveShapeBox.setItemText(0, _translate("MainWindow", "Sine Wave"))
        self.waveShapeBox.setItemText(1, _translate("MainWindow", "Square Pulse"))
        self.label_4.setText(_translate("MainWindow", "Train Pattern Repeats"))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Train Duration (s) "))
        self.label_7.setText(_translate("MainWindow", "Hz"))
        self.label_8.setText(_translate("MainWindow", "s"))
        self.trainDurEdit.setText(_translate("MainWindow", "60"))
        self.label_5.setText(_translate("MainWindow", "if pulse, width ="))
        self.pulseWidthEdit.setText(_translate("MainWindow", "33"))
        self.pretrainDurEdit.setText(_translate("MainWindow", "60"))
        self.label_2.setText(_translate("MainWindow", "Pre-Train Duration (s)"))
        self.waitEdit.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "wait between:"))
        self.label_11.setText(_translate("MainWindow", "s"))
        self.freqPatternEdit.setText(_translate("MainWindow", "4,8"))
        self.label_3.setText(_translate("MainWindow", "Train Frequency Pattern (Separated by ,)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Settings.setText(_translate("MainWindow", "Load Settings..."))
        self.actionSave_Settings.setText(_translate("MainWindow", "Save Settings..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

