# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ardu_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 136)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.patternRepeatsBox = QtWidgets.QSpinBox(self.centralwidget)
        self.patternRepeatsBox.setMinimum(1)
        self.patternRepeatsBox.setMaximum(999)
        self.patternRepeatsBox.setObjectName("patternRepeatsBox")
        self.gridLayout.addWidget(self.patternRepeatsBox, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.pulseWidthEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pulseWidthEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pulseWidthEdit.setObjectName("pulseWidthEdit")
        self.gridLayout.addWidget(self.pulseWidthEdit, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 6, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 3, 1, 1, 1)
        self.freqPatternEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.freqPatternEdit.setObjectName("freqPatternEdit")
        self.gridLayout.addWidget(self.freqPatternEdit, 1, 3, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 6, 1, 1)
        self.trainDurEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trainDurEdit.setObjectName("trainDurEdit")
        self.gridLayout.addWidget(self.trainDurEdit, 0, 1, 1, 2)
        self.portBox = QtWidgets.QComboBox(self.centralwidget)
        self.portBox.setObjectName("portBox")
        self.gridLayout.addWidget(self.portBox, 3, 2, 1, 5)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 3, 0, 1, 1)
        self.pretrainDurEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pretrainDurEdit.setObjectName("pretrainDurEdit")
        self.gridLayout.addWidget(self.pretrainDurEdit, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 6, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 336, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arduino Stimulator"))
        self.label.setText(_translate("MainWindow", "Train Duration (s) "))
        self.label_5.setText(_translate("MainWindow", "Pulse width (% of period)"))
        self.label_2.setText(_translate("MainWindow", "Pre-Train Duration (s)"))
        self.pulseWidthEdit.setText(_translate("MainWindow", "33"))
        self.label_3.setText(_translate("MainWindow", "Train Frequency Pattern (Separated by ,)"))
        self.label_4.setText(_translate("MainWindow", "Train Pattern Repeats"))
        self.label_6.setText(_translate("MainWindow", "%"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.freqPatternEdit.setText(_translate("MainWindow", "4,8"))
        self.label_8.setText(_translate("MainWindow", "s"))
        self.label_7.setText(_translate("MainWindow", "Hz"))
        self.trainDurEdit.setText(_translate("MainWindow", "60"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.pretrainDurEdit.setText(_translate("MainWindow", "60"))
        self.label_9.setText(_translate("MainWindow", "s"))

